#!/bin/sh
while true; do
	method="`uci -q get yota.@yotareboot[0].method`"
	hiip="`uci -q get yota.@yotareboot[0].hiip`"
	telip="`uci -q get yota.@yotareboot[0].telip`"
	telport="`uci -q get yota.@yotareboot[0].telport`"
	adbip="`uci -q get yota.@yotareboot[0].adbip`"
	adbport="`uci -q get yota.@yotareboot[0].adbport`"
	usbreset="`uci -q get yota.@yotareboot[0].usbreset`"
	if wget captive.apple.com -q -O - | grep -q 'tethering.svg'; then
		case $method in
			reboot)
				reboot
				;;
			hiconn)
				# заготовка для реконнекта через HiLink API
				#
				#
				# нужно из /api/webserver/SesTokInfo взять SesInfo и TokInfo
				# SesInfo передаем как кукис
				# TokInfo как хидер __RequestVerificationToken
				#
				# посылкаем два запроса:
				# <?xml version="1.0" encoding="UTF-8"?><request><dataswitch>0</dataswitch></request>
				# на
				# /api/dialup/mobile-dataswitch
				# для дисконнекта
				#
				# и далее
				# <?xml version="1.0" encoding="UTF-8"?><request><dataswitch>1</dataswitch></request>
				# на
				# /api/dialup/mobile-dataswitch
				# для коннекта
				;;
			hireb)
				# заготовка для ребута через HiLink API
				#
				#
				# нужно из /api/webserver/SesTokInfo взять SesInfo и TokInfo
				# SesInfo передаем как кукис
				# TokInfo как хидер __RequestVerificationToken
				#
				# посылкаем запрос:
				# <?xml version="1.0" encoding="UTF-8"?><request><Control>1</Control></request>
				# на
				# /api/device/control
				;;
			telnet)
				[ "$telip" -a "$telport" ] && (echo reboot; sleep 1) | nc $telip $telport & (sleep 1; kill `pidof $(ps | grep "nc $telip $telport" | grep -v 'grep')`)
				;;
			adbreboot)
				[ "$adbip" -a "$adbport" ] && adb connect $adbip:$adport
				adb reboot
				;;
			adbshellreboot)
				[ "$adbip" -a "$adbport" ] && adb connect $adbip:$adport
				adb shell reboot
				;;
			adbatreset)
				[ "$adbip" -a "$adbport" ] && adb connect $adbip:$adport
				adb shell atc AT^RESET
				;;
			adbatcfun)
				[ "$adbip" -a "$adbport" ] && adb connect $adbip:$adport
				adb shell atc AT+CFUN=1,1
				;;
			atreset)
				devices=$(ls /dev/ttyUSB* /dev/cdc-wdm* /dev/ttyACM* /dev/ttyHS* 2>/dev/null | sort -r);
				for d in $devices; do
					DEVICE=$d gcom -s /etc/gcom/probeport.gcom > /dev/null 2>&1
					if [ $? = 0 ]; then
						DEVICE="$d"
						break
					fi
				done
				COMMAND=AT^RESET gcom -d $DEVICE -s /etc/gcom/runcommand.gcom
				;;
			atcfun)
				devices=$(ls /dev/ttyUSB* /dev/cdc-wdm* /dev/ttyACM* /dev/ttyHS* 2>/dev/null | sort -r);
				for d in $devices; do
					DEVICE=$d gcom -s /etc/gcom/probeport.gcom > /dev/null 2>&1
					if [ $? = 0 ]; then
						DEVICE="$d"
						break
					fi
				done
				COMMAND=AT+CFUN=1,1 gcom -d $DEVICE -s /etc/gcom/runcommand.gcom
				;;
			usbreset)
				[ "$usbreset" ] && usbreset "$usbreset"
				;;
			network)
				/etc/init.d/network restart
				;;
		esac
	fi
	sleep 10
done

