#!/bin/sh

[ "$ACTION" = ifup ] || exit 0

/etc/init.d/yotaban enabled && {
	[ -f /tmp/yotaban ] && {
		# remove old records
		while read -r i; do
			[ "`echo $i | sed -n '/^#.*$/p'`" ] && continue
			iptables -D FORWARD -d $i -j DROP
		done < /tmp/yotaban
	}
	
	# update records
	#wget -O /tmp/yotaban http://cdn.rawgit.com/TTLMaster/yota-ban-list/master/list.txt
	wget -O /tmp/yotaban https://raw.githubusercontent.com/TTLMaster/yota-ban-list/master/list.txt
	
	# add new records
	while read -r i; do
		[ "`echo $i | sed -n '/^#.*$/p'`" ] && continue
		iptables -I FORWARD -d $i -j DROP
	done < /tmp/yotaban
}
