#!/bin/sh /etc/rc.common

START=19
VALUE="`uci -q get yota.@ttl[0].value`"
MODE="`uci -q get yota.@ttl[0].mode`"

start() {
	iptables -t mangle -N yotattl
	iptables -t mangle -A POSTROUTING -j yotattl
	iptables -t mangle -A yotattl -j TTL --ttl-$MODE $VALUE
}

stop() {
	iptables -t mangle -D POSTROUTING -j yotattl
	iptables -t mangle -F yotattl
	iptables -t mangle -X yotattl
}
